### ISSUE TITLE
Ajouter des widgets pour les home screens.

### ISSUE THREAD

**Issue by margotfrison** [pfrison/Polytime#4]
Ajouter des widgets pour les home screens.

**Comment by pfrison** [comment]
Résolu !
La modification prendra effet lors de la prochaine mise à jour.

En plus du problème résolu, le dimensionnement de l'emploi du temps ne se fait plus avec un vulgaire setHeight() mais directement par une contrainte avec le layout : nous avons gagné en flexibilité.

**Comment by margotfrison** [comment]
Oops ! Mauvaise issue...

**Comment by margotfrison** [comment]
Les widgets seront disponibles lors de la prochaine mise à jour.

Un aperçu rapide :
![screenshot_20171015-024113](https://user-images.githubusercontent.com/32441001/31580565-f19f7d12-b153-11e7-9220-951fc84d75c0.png)
